# Generated by Django 2.2.6 on 2019-10-30 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='Turma',
            new_name='turma',
        ),
    ]
