# Generated by Django 2.2.6 on 2019-10-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191030_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Turma'),
        ),
    ]
