# Generated by Django 2.2.6 on 2019-10-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turma_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='num',
        ),
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='', max_length=10, verbose_name='Nome'),
        ),
    ]
