# Generated by Django 2.2.6 on 2019-10-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191030_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor_curso'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Hora/aula'),
        ),
    ]
